Insert into planet_name values ('A','Earth');
Insert into planet_name values ('B','Moon');
Insert into planet_name values ('C','Jupiter');
Insert into planet_name values ('D','Venus');
Insert into planet_name values ('E','Mars');
Insert into planet_name values ('F','Saturn');
Insert into planet_name values ('G','Uranus');
Insert into planet_name values ('H','Pluto');
Insert into planet_name values ('I','Neptune');
Insert into planet_name values ('J','Mercury');
Insert into planet_name values ('K','Alpha Centauri');
Insert into planet_name values ('L','Luhman 16');
Insert into planet_name values ('M','Epsilon Eridani');
Insert into planet_name values ('N','Groombridge 34');
Insert into planet_name values ('O','Epsilon Indi');
Insert into planet_name values ('P','Tau Ceti');
Insert into planet_name values ('Q','Kapteyn''s star');
Insert into planet_name values ('R','Gliese 687');
Insert into planet_name values ('S','Gliese 674');
Insert into planet_name values ('T','Gliese 876#');
Insert into planet_name values ('U','Gliese 832');
Insert into planet_name values ('V','Fomalhaut');
Insert into planet_name values ('W','Virginis');
Insert into planet_name values ('X','HD 102365');
Insert into planet_name values ('Y','Gliese 176');
Insert into planet_name values ('Z','Gliese 436');
Insert into planet_name values ('A''','Pollux');
Insert into planet_name values ('B''','Gliese 86');
Insert into planet_name values ('C''','HIP 57050');
Insert into planet_name values ('D''','Piscium');
Insert into planet_name values ('E''','GJ 1214');
Insert into planet_name values ('F''','Upsilon Andromedae');
Insert into planet_name values ('G''','Gamma Cephei');
Insert into planet_name values ('H''','HD 176051');
Insert into planet_name values ('I''','Gliese 317');
Insert into planet_name values ('J''','HD 38858');
Insert into planet_name values ('K''','Ursae Majoris');

Insert into route values (1,'A','B',0.44);
Insert into route values (2,'A','C',1.89);
Insert into route values (3,'A','D',0.1);
Insert into route values (4,'B','H',2.44);
Insert into route values (5,'B','E',3.45);
Insert into route values (6,'C','F',0.49);
Insert into route values (7,'D','L',2.34);
Insert into route values (8,'D','M',2.61);
Insert into route values (9,'H','G',3.71);
Insert into route values (10,'E','I',8.09);
Insert into route values (11,'F','J',5.46);
Insert into route values (12,'F','K',3.67);
Insert into route values (13,'G','Z',5.25);
Insert into route values (14,'I','Z',13.97);
Insert into route values (15,'I','J',14.78);
Insert into route values (16,'L','T',15.23);
Insert into route values (17,'T','N',10.43);
Insert into route values (18,'T','S',14.22);
Insert into route values (19,'S','O',6.02);
Insert into route values (20,'O','U',5.26);
Insert into route values (21,'J','R',12.34);
Insert into route values (22,'R','P',10.1);
Insert into route values (23,'R','L''',9.95);
Insert into route values (24,'Z','Y',18.91);
Insert into route values (25,'Y','Q',22.04);
Insert into route values (26,'Q','X',10.51);
Insert into route values (27,'L''','X',23.61);
Insert into route values (28,'X','K''',19.94);
Insert into route values (29,'P','U',9.31);
Insert into route values (30,'U','K''',21.23);
Insert into route values (31,'U','J''',25.96);
Insert into route values (32,'J''','V',3.16);
Insert into route values (33,'K''','V',20.42);
Insert into route values (34,'J''','I''',17.1);
Insert into route values (35,'Y','A''',19.52);
Insert into route values (36,'A''','B''',31.56);
Insert into route values (37,'B''','C''',23.13);
Insert into route values (38,'K''','W',28.89);
Insert into route values (39,'W','C''',10.64);
Insert into route values (40,'W','E''',36.19);
Insert into route values (41,'C''','D''',36.48);
Insert into route values (42,'E''','E''',41.26);
Insert into route values (43,'E''','F''',42.07);
Insert into route values (44,'F''','G''',17.63);
Insert into route values (45,'G''','H''',40.48);
