CREATE SCHEMA INTERSTELLAR_TRANSPORT;

--DROP TABLE IF EXISTS PLANET_NAME;

CREATE TABLE PLANET_NAME (
    PLANET_NODE VARCHAR(255) NOT NULL,
    PLANET_NAME VARCHAR(255) NOT NULL,
    PRIMARY KEY (PLANET_NODE)
);

--DROP TABLE IF EXISTS ROUTE;

CREATE TABLE ROUTE (
    ROUTE_ID INT NOT NULL, 
	--AUTO_INCREMENT,
    PLANET_ORIGIN VARCHAR(255) NOT NULL,
    PLANET_DESTINATION VARCHAR(255) NOT NULL,
    PLANET_DISTANCE DOUBLE, 
    PRIMARY KEY (ROUTE_ID)
);

--DROP TABLE IF EXISTS TRAFFIC;

CREATE TABLE TRAFFIC (
    TRAFFIC_ID INT NOT NULL ,
	--AUTO_INCREMENT,
    PLANET_ORIGIN VARCHAR(255) NOT NULL,
    PLANET_DESTINATION VARCHAR(255) NOT NULL,
	TRAFFIC DOUBLE,
    PRIMARY KEY (TRAFFIC_ID)
);